### ISSUE TITLE
instance-balanced Training config file for Places365

### ISSUE THREAD

**Issue by jiequancui** [facebookresearch/classifier-balancing#2]
Hello,

is there instance-balanced training config file for Places365 ?

**Comment by bingykang** [comment]
Sorry, it's not included in the current version. But one can easily create one by modifying from ImageNet_LT or iNaturalist. Note that for instance-balanced training on Places365, we only train the last block, which means one should modify the code correspondingly by adding condition here https://github.com/facebookresearch/classifier-balancing/blob/master/run_networks.py#L119.

**Comment by jiequancui** [comment]
Big thanks for your reply.

**Comment by TonyLianLong** [comment]
@bingykang I'm wondering how many epochs you're using to train Places-LT. Is it 30 epochs as in OLTR, or 90 epochs as described in your paper?

**Comment by TonyLianLong** [comment]
> Note that for instance-balanced training on Places365, we only train the last block, which means one should modify the code correspondingly by adding condition here https://github.com/facebookresearch/classifier-balancing/blob/master/run_networks.py#L119.

In addition, by `only train the last block`, do you mean in **stage 1** (feature training stage) you freeze everything before last `BottleNeck` or `layer4`?

**Comment by jiequancui** [comment]
Very interesting work. Thank you !

**Comment by Charlie4zc** [comment]
Since `OLTR/config/Places_LT/stage_1.py` set ''fix' = False, 'use_modulatedatt': False, 'use_fc': True` for finetuning, i'm wondering how

>  code correspondingly by adding condition here https://github.com/facebookresearch/classifier-balancing/blob/master/run_networks.py#L119.

was done?
