### ISSUE TITLE
Shouldn't the Stage1 weights be true in config setting?

### ISSUE THREAD

**Issue by abdullahjamal** [facebookresearch/classifier-balancing#3]
https://github.com/facebookresearch/classifier-balancing/blob/master/config/ImageNet_LT/cls_crt.yaml#L23

Here for cRT, shouldn't the stage1 weights be true for classifier learning stage?

**Comment by bingykang** [comment]
This parameter is used in the original OLTR code but discarded in our implementation. The parameter fixing is done through https://github.com/facebookresearch/classifier-balancing/blob/master/run_networks.py#L115-L120.
